version: "3.9"

services:
  caddy:
    image: erfianugrah/revista-4:1.1.5
    hostname: revista
    container_name: revista
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 128M
    volumes:
      - /mnt/user/data/revista/log:/var/log
    environment:
      - TZ=Asia/Singapore
    expose:
      - 4321
    networks:
      servarr:
        ipv4_address: 172.66.0.2

networks:
  servarr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.66.0.0/16
