name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Deno Deploy를 통한 인증에 필요
      contents: read # 저장소를 복제하는 데 필요

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # npm을 사용하지 않나요? `npm ci`를 `yarn install` 또는 `pnpm i`로 변경하세요.
      - name: Install dependencies
        run: npm ci

      # npm을 사용하지 않나요? `npm run build`를 `yarn build` 또는 `pnpm run build`로 변경하세요.
      - name: Build Astro
        run: npm run build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: photoby-xyz # TODO: Deno Deploy 프로젝트 이름으로 교체
          entrypoint: server/entry.mjs
          root: dist